const DEEP_PURPLE = "#704672";
const DARK_GREEN = "#00A372";
const ORANGE = "#ED7D3A";
const BACKGROUND_COLOR = "#1D1E2C";
const USER_ID = "styyU96y1esfusrGM";

export { DEEP_PURPLE, DARK_GREEN, ORANGE, BACKGROUND_COLOR, USER_ID };
